version: '3'

services:
  proxy:
    image: nginx:latest
    ports:
      - 8443:8443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/certs:/etc/nginx/ssl/:ro
      - ./nginx/www/:/www/:ro